name: movie_booking_app
description: ""
version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  http: ^1.2.1
  carousel_slider: ^4.2.1
  flutter_localization: ^0.2.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  flutter_inappwebview: ^6.0.0
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.7.0
  date_picker_timeline: ^1.2.6
  image_picker: ^0.8.5+3
  image_cropper: ^1.5.0
  sprintf: ^7.0.0
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0
  translator: ^1.0.0
  webview_flutter: ^4.8.0
  font_awesome_flutter: ^10.7.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/banner/
    - assets/icons/
    - assets/svg/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
