name: movie_booking_app
description: ""
version: 1.0.0+1
environment:
  sdk: ">=3.4.0 <4.0.0"
dependencies:
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  carousel_slider: ^4.2.1
  flutter_localization: ^0.2.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  youtube_player_flutter: ^9.0.1
  flutter_inappwebview: ^6.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_svg: ^2.0.10+1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
