name: movie_ticket_scanner
description: "Application to support QR Code scanning of STU cinemas movie ticket booking application"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  qr_code_scanner: ^1.0.1
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  http: ^1.1.2
  intl: ^0.19.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/svg/
